version: "3.4"

networks:
  frontend:
    external: true
  app:
    driver: bridge
    internal: false

services:
  nginx:
    image: nginxinc/nginx-unprivileged:alpine
    networks:
      - app
      - frontend
    depends_on:
      - node
    ports:
      - '8080'
    volumes:
      - ${PWD}/.docker/vhost.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/app:delegated
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=frontend"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${COMPOSE_DOMAIN}`)"
      #      HTTPS config - uncomment to enable redirect from :80 to :443
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

  node:
    image: node:20
    command: yarn start
    networks:
      - app
    working_dir: /app
    ports: 
      - '3000'
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app:delegated
    healthcheck:
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 60s

  playwright:
    # https://playwright.dev/docs/docker
    # This Playwright version should match the one in `package.json`.
    image: mcr.microsoft.com/playwright:v1.44.1
    command: yarn playwright test
    networks:
      - app
    depends_on:
      - nginx
    volumes:
      - .:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
    working_dir: /app
